FROM ruby:3.1.2-alpine3.16

# WORKDIR /app

RUN apk update && apk add bash git build-base freetds-dev freetds neovim openssl

WORKDIR /app

COPY . .

RUN bundle install

# RUN rm config/credentials.yml.enc

EXPOSE 3000