# Stage 1: Build stage
FROM ruby:3.1.2 AS builder

# Set the working directory inside the container
WORKDIR /app

# Install dependencies
RUN apt-get update && \
    apt-get install -y nodejs freetds-dev freetds-bin freetds-common

# Copy Gemfile and Gemfile.lock to the working directory
COPY Gemfile Gemfile.lock ./

# Install gems
RUN gem install bundler && bundle install

# Copy the rest of the application code
COPY . .

# Stage 2: Final stage
FROM ruby:3.1.2

# Set the working directory inside the container
WORKDIR /app

# Copy built application from the builder stage
COPY --from=builder /app .

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the Rails server
CMD ["rails", "server", "-b", "0.0.0.0"]