ARG RUBY_VERSION=3.1.2
FROM ruby:$RUBY_VERSION-alpine3.16

# Instalando librerias de alpine
RUN apk update && apk add bash git build-base \
  freetds-dev freetds neovim openssl

# La aplicación rails vivirá aqui:
WORKDIR /app

# Set production environment
ENV RAILS_LOG_TO_STDOUT="1" \
    RAILS_SERVE_STATIC_FILES="true" \
    RAILS_ENV="production" \
    BUNDLE_WITHOUT="development"

# Instalando gemas
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copiar el codigo de la aplicación
COPY . .

# Precompile bootsnap code for faster boot times
RUN bundle exec bootsnap precompile --gemfile app/ lib/

# Precompiling assets for production without requiring secret RAILS_MASTER_KEY
RUN SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile

# RUN rm config/credentials.yml.enc

EXPOSE 3000

# Ejecutando aplicación rails
CMD ["./bin/rails", "server"]