# BIWEEKLY-BACK DATABASE SETTINGS

default: &default
  adapter: sqlserver
  encoding: utf8 

development:
  <<: *default  
  host: localhost
  port: 1433
  username: <%= ENV["DB_PASSWORD_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD_DEV"] %> 
  database: biweekly_back_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>  

# test:
#   <<: *default
#   # host: localhost 
#   port: 1433
#   database: biweekly_back_test
#   username: test
#   password: test

production:
  <<: *default
  host: sql_server_container
  # host: localhost
  port: 1433
  database: biweekly_back_production
  username: <%= ENV["BIWEEKLY_BACK_DATABASE_USERNAME"] %>
  password: <%= ENV["BIWEEKLY_BACK_DATABASE_PASSWORD"] %>
  timeout: 1500

