# BIWEEKLY-BACK DATABASE SETTINGS

default: &default
  adapter: sqlserver
  encoding: utf8
  username: appBiweekly
  password: <%= ENV["DB_PASSWORD_DEV"] %>
  host: localhost

development:
  <<: *default  
  database: biweekly_back_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 1433

test:
  <<: *default
  database: biweekly_back_test

production:
  <<: *default
  host: 89.116.49.98
  database: biweekly_back_production
  username: biweeklyUserProd
  password: <%= ENV["BIWEEKLY_BACK_DATABASE_PASSWORD"] %>
  timeout: 1500
